//$Header: /oftp2/de/mendelson/util/security/csr/JDialogCSRTypeSelection.java 4     20/11/24 14:13 Heller $
package de.mendelson.util.security.csr;

import de.mendelson.util.MecFileChooser;
import de.mendelson.util.MecResourceBundle;
import de.mendelson.util.MendelsonMultiResolutionImage;
import de.mendelson.util.TextOverlay;
import de.mendelson.util.security.cert.clientserver.CSRGenerationRequest;
import java.util.MissingResourceException;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/*
 * Copyright (C) mendelson-e-commerce GmbH Berlin Germany
 *
 * This software is subject to the license agreement set forth in the license.
 * Please read and agree to all terms before using this software.
 * Other product and brand names are trademarks of their respective owners.
 */
/**
 * Dialog to select the CSR type that should be genrated
 *
 * @author S.Heller
 * @version $Revision: 4 $
 */
public class JDialogCSRTypeSelection extends JDialog {

    protected final static MendelsonMultiResolutionImage IMAGE_CA
            = MendelsonMultiResolutionImage.fromSVG(
                    "/de/mendelson/util/security/cert/gui/ca.svg",
                    32);

    public final static int SELECTION_CANCEL = 0;
    public final static int SELECTION_PKCS10 = CSRGenerationRequest.SELECTION_PKCS10;
    public final static int SELECTION_CRMF = CSRGenerationRequest.SELECTION_CRMF;
    private int selection = SELECTION_CANCEL;
    private String selectedFilename = "";

    /**
     * ResourceBundle to localize the GUI
     */
    private final MecResourceBundle rb;

    /**
     * Creates new form JDialogPartnerConfig
     *
     */
    public JDialogCSRTypeSelection(JFrame parent) {
        super(parent, true);
        //load resource bundle
        try {
            this.rb = (MecResourceBundle) ResourceBundle.getBundle(
                    ResourceBundleCSRTypeSelection.class.getName());
        } catch (MissingResourceException e) {
            throw new RuntimeException("Oops..resource bundle "
                    + e.getClassName() + " not found.");
        }
        this.setTitle(this.rb.getResourceString("title"));
        initComponents();
        this.setMultiresolutionIcons();
        TextOverlay.addTo(this.jTextFieldExportFile,
                this.rb.getResourceString("label.exportfile.hint"));
        this.getRootPane().setDefaultButton(this.jButtonOk);
        this.setButtonState();
    }

    /**
     * Overwrite the designers icons by multi resolution icons
     */
    private void setMultiresolutionIcons() {
        this.jLabelImage.setIcon(new ImageIcon(IMAGE_CA.toMinResolution(32)));
    }

    /**
     * @return the selection
     */
    public int getSelection() {
        return selection;
    }

    private void computeSelection() {
        if (this.jRadioButtonPKCS10.isSelected()) {
            this.selection = SELECTION_PKCS10;
        }
        if (this.jRadioButtonCRMF.isSelected()) {
            this.selection = SELECTION_CRMF;
        }
        this.selectedFilename = this.jTextFieldExportFile.getText();
    }

    private void setButtonState(){
        this.jButtonOk.setEnabled( this.jTextFieldExportFile.getText().trim().length() > 0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupImport = new javax.swing.ButtonGroup();
        jPanelEdit = new javax.swing.JPanel();
        jLabelImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jRadioButtonPKCS10 = new javax.swing.JRadioButton();
        jRadioButtonCRMF = new javax.swing.JRadioButton();
        jLabelWhatToExport = new javax.swing.JLabel();
        jLabelPKCS10 = new javax.swing.JLabel();
        jLabelCRMFPOPSig = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelFilename = new javax.swing.JPanel();
        jLabelExportfile = new javax.swing.JLabel();
        jTextFieldExportFile = new javax.swing.JTextField();
        jButtonSelectExportFile = new javax.swing.JButton();
        jPanelSpace78273 = new javax.swing.JPanel();
        jPanelSpace23445 = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelEdit.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanelEdit.setLayout(new java.awt.GridBagLayout());

        jLabelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/mendelson/util/security/cert/gui/missing_image32x32.gif"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        jPanelEdit.add(jLabelImage, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        jPanelEdit.add(jPanel3, gridBagConstraints);

        buttonGroupImport.add(jRadioButtonPKCS10);
        jRadioButtonPKCS10.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanelEdit.add(jRadioButtonPKCS10, gridBagConstraints);

        buttonGroupImport.add(jRadioButtonCRMF);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanelEdit.add(jRadioButtonCRMF, gridBagConstraints);

        jLabelWhatToExport.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabelWhatToExport.setText(this.rb.getResourceString( "info"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanelEdit.add(jLabelWhatToExport, gridBagConstraints);

        jLabelPKCS10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelPKCS10.setText(this.rb.getResourceString( "label." + SELECTION_PKCS10));
        jLabelPKCS10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPKCS10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelEdit.add(jLabelPKCS10, gridBagConstraints);

        jLabelCRMFPOPSig.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelCRMFPOPSig.setText(this.rb.getResourceString( "label." + SELECTION_CRMF));
        jLabelCRMFPOPSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCRMFPOPSigMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelEdit.add(jLabelCRMFPOPSig, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 15, 5);
        jPanelEdit.add(jPanel1, gridBagConstraints);

        jPanelFilename.setLayout(new java.awt.GridBagLayout());

        jLabelExportfile.setText(this.rb.getResourceString( "label.exportfile"));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelFilename.add(jLabelExportfile, gridBagConstraints);

        jTextFieldExportFile.setMinimumSize(new java.awt.Dimension(280, 22));
        jTextFieldExportFile.setPreferredSize(new java.awt.Dimension(280, 22));
        jTextFieldExportFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldExportFileKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelFilename.add(jTextFieldExportFile, gridBagConstraints);

        jButtonSelectExportFile.setText("..");
        jButtonSelectExportFile.setMargin(new java.awt.Insets(2, 10, 2, 10));
        jButtonSelectExportFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectExportFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanelFilename.add(jButtonSelectExportFile, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanelFilename.add(jPanelSpace78273, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanelEdit.add(jPanelFilename, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelEdit.add(jPanelSpace23445, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanelEdit, gridBagConstraints);

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jButtonOk.setText(this.rb.getResourceString( "button.ok" ));
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelButtons.add(jButtonOk, gridBagConstraints);

        jButtonCancel.setText(this.rb.getResourceString( "button.cancel" ));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelButtons.add(jButtonCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanelButtons, gridBagConstraints);

        setSize(new java.awt.Dimension(636, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        this.computeSelection();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jLabelPKCS10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPKCS10MouseClicked
        this.jRadioButtonPKCS10.setSelected(true);
    }//GEN-LAST:event_jLabelPKCS10MouseClicked

    private void jLabelCRMFPOPSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCRMFPOPSigMouseClicked
        this.jRadioButtonCRMF.setSelected(true);
    }//GEN-LAST:event_jLabelCRMFPOPSigMouseClicked

    private void jTextFieldExportFileKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldExportFileKeyReleased
        this.setButtonState();
    }//GEN-LAST:event_jTextFieldExportFileKeyReleased

    private void jButtonSelectExportFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectExportFileActionPerformed
        JFrame parentFrame = (JFrame)SwingUtilities.getAncestorOfClass(JFrame.class, this);
        MecFileChooser chooser = new MecFileChooser(parentFrame,
                        this.rb.getResourceString("label.selectcsrfile"));
        chooser.browseFilename(this.jTextFieldExportFile);
        this.setButtonState();
    }//GEN-LAST:event_jButtonSelectExportFileActionPerformed

    /**
     * @return the selectedFilename
     */
    public String getSelectedFilename() {
        return selectedFilename;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupImport;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonSelectExportFile;
    private javax.swing.JLabel jLabelCRMFPOPSig;
    private javax.swing.JLabel jLabelExportfile;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelPKCS10;
    private javax.swing.JLabel jLabelWhatToExport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelEdit;
    private javax.swing.JPanel jPanelFilename;
    private javax.swing.JPanel jPanelSpace23445;
    private javax.swing.JPanel jPanelSpace78273;
    private javax.swing.JRadioButton jRadioButtonCRMF;
    private javax.swing.JRadioButton jRadioButtonPKCS10;
    private javax.swing.JTextField jTextFieldExportFile;
    // End of variables declaration//GEN-END:variables

}
