//$Header: /as2/de/mendelson/util/wizard/category/JPanelCategory.java 10    11/02/25 13:40 Heller $Revision: 7 $
package de.mendelson.util.wizard.category;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/*
 * Copyright (C) mendelson-e-commerce GmbH Berlin Germany
 *
 * This software is subject to the license agreement set forth in the license.
 * Please read and agree to all terms before using this software.
 * Other product and brand names are trademarks of their respective owners.
 */

/**
 * Panel to select categories
 * @author S.Heller
 * @version $Revision: 10 $
 */

public class JPanelCategory extends JPanel implements ListSelectionListener{
    
    private Category category = null;
    
    /**Listens to a double click event*/
    private CategorySelectionListener listener = null;
    
    /** Creates new form JPanelCategory
     *@param category Category that is linked with this tab
     */
    public JPanelCategory( Category category, CategorySelectionListener listener ){
        super();
        initComponents();
        this.category = category;
        this.jListSubcategories.setCellRenderer( new ListCellRendererSubcategories() );
        Subcategory[] subcategories = category.getSubcategories();
        this.jListSubcategories.setListData( subcategories );
        this.jListSubcategories.setVisibleRowCount( 0 );
        
        MouseListener mouseListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = jListSubcategories.locationToIndex(e.getPoint());
                    informListenerItemSelected( index );
                }
            }
        };
        this.jListSubcategories.addMouseListener( mouseListener );
        this.jListSubcategories.addListSelectionListener( this );
        this.listener = listener;
        this.jListSubcategories.setSelectedIndex(0);
    }
    
    /**Returns the category attached to this panel*/
    public Category getCategory(){
        return( this.category );
    }
    
    /**Returns the index of the subcategory that has been selected
     */
    public int getSelectedSubCategoryIndex(){
        return( this.jListSubcategories.getSelectedIndex() );
    }
    
    /**Informs the listeners that an item has been selected. This could happen
     *via a double click or the OK button
     */
    private synchronized void informListenerItemSelected( int index ){
        this.listener.selectionPerformed(
                new CategorySelectionListener.CategorySelectionEvent(
                this.category, this.category.getSubcategories()[index],
                index ));
    }
    
    /**Makes this a ListSelectionListener
     */
    public void valueChanged( ListSelectionEvent listSelectionEvent) {
        Subcategory subcategory
                = (Subcategory)this.jListSubcategories.getSelectedValue();
        this.jTextFieldInfo.setText( subcategory.getDescription() );
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane = new javax.swing.JScrollPane();
        jListSubcategories = new javax.swing.JList();
        jTextFieldInfo = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jListSubcategories.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        jListSubcategories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSubcategories.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jListSubcategories.setVisibleRowCount(0);
        jScrollPane.setViewportView(jListSubcategories);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane, gridBagConstraints);

        jTextFieldInfo.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(jTextFieldInfo, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListSubcategories;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextFieldInfo;
    // End of variables declaration//GEN-END:variables
    
}
